### ISSUE TITLE
Update OCPP 2.0

### ISSUE THREAD

**Issue by pioneersteffen** [Argonne-National-Laboratory/node-red-contrib-ocpp#10]
Hi laboratory team,

many thanks to providing this awesome Node Red flow!

Are planning to update to OCCP 2.0 and also supporting OSCP 2.0?

Many thanks in advance!

Best Regards 
Steffen

**Comment by Loetfi** [comment]
great !!

**Comment by jayharper** [comment]
@pioneersteffen yes, we have plans to update this node to support OCPP 2.0 but it might not be for another year or so given our current priorities.
