### ISSUE TITLE
How can i run the server?

### ISSUE THREAD

**Issue by BurakOgutken** [Argonne-National-Laboratory/node-red-contrib-ocpp#16]
Hello,

i dont understand ocpp-server.js is work or not i just write node ocpp-server.js nothing happend
someone help me how can start server ?

thanks

**Comment by bnystrom** [comment]
This is a Node-Red set of nodes. You need to install it from Node-Red.
There is an example flow that shows both a server and charge point.
This is not a stand alone OCPP server.

Best Regards
Bryan Nystrom

**Comment by 204maker** [comment]
How do I setup the node-red OCPP server so it can communicate to the charge point?
The examples do not show anything on the debug messages.
