### ISSUE TITLE
Flow crashes when using wrong URL

### ISSUE THREAD

**Issue by kobe87** [Argonne-National-Laboratory/node-red-contrib-ocpp#23]
When you are using the "CP client JSON" Node and type in the wrong URL for the central system the whole flow crashes. Then you have to change the URL in the JSON file before you can restart Node-Red.

**Comment by osulivanDE** [comment]
Same Problem here. Node-Red crashed, and had to restore the configfile from backup to get it back working.

**Comment by bnystrom** [comment]
Can you verify what version of the node-red-ocpp nodes you are using?
Also, can you give me an example of the URL you typed in? Was it a badly
formed URL, or just that the URL didn't really exist or point to a valid
CSMS backend?

Best Regards
Bryan Nystrom

**Comment by bnystrom** [comment]
Fix added in v1.3.3
