### ISSUE TITLE
Smart Charging functions?

### ISSUE THREAD

**Issue by tsknightstorm** [Argonne-National-Laboratory/node-red-contrib-ocpp#24]
Do you plan to ad smart charging functions like control the charging current of a charging station?

If we would have this function it should be possible to realise a load management in node-red what would make it very flexible to connect it to different systems over different manufacturer brands.

**Comment by bnystrom** [comment]
OCPP 1.6 supports "setChargingProfile", and therefore can be sent into the "CS Request JSON" node.
