### ISSUE TITLE
Feature-Request Basic Auth 

### ISSUE THREAD

**Issue by osulivanDE** [Argonne-National-Laboratory/node-red-contrib-ocpp#38]
Is there a way to connect the nodes to a Basic Auth websocket?

**Comment by bnystrom** [comment]
Try:

ws://__username:password__@my.centralurl.com:1234/route

I've added basic auth in the upcoming 2.0.1 release, so I may backroll it into the 1.6 release also, but for now the above "should" work? Let me know if it does.

**Comment by osulivanDE** [comment]
This works. Thank you.
