### ISSUE TITLE
WebSocket is not open: readyState 3

### ISSUE THREAD

**Issue by yonas124** [Argonne-National-Laboratory/node-red-contrib-ocpp#4]
Hello, I'm currently testing the 'CS server' with 2 chargebox connected. When I send command over 'CS request JSON' node, occasionally it gives "error: WebSocket is not open: readyState 3 (CLOSED)" and I had to restart the flow.

Any idea?

**Comment by mingyi621** [comment]
Uncomment line 351 and 352 in ocpp/ocpp-server.js can resolve the issue.

**Comment by yonas124** [comment]
After days lf observing, it seems like the websocket error is no longer there but from time to time the Charging Station got disconnected and the flow must be restarted.
Any idea why?

I put 2 hours in nodered websocket timeout setting.

**Comment by gvregulvar** [comment]
Hello,

i also had the same problem recently. It usually happens over night. When i wake up in the morning, i can't send commands to the charging stations.

did the 2 hours timeout work out for you @yonas124 ?

**Comment by yonas124** [comment]
@gvregulvar I put periodic 'GetConfig' command to make sure the socket is ready to receive command but no, the timout didn't work for me, CS disconnected after 1-2 hours randomly. I ended up reverting to its default condition, no timeout configured.

It's less stable with 2 or more CS connected.

What's your setup?

**Comment by gvregulvar** [comment]
@yonas124 I have 2 charging stations, OCPP 1.6j. I wish i had 4+ to test, but i dont think its going to happen for now. The server is on a mini-pc with a lightweight linux and on the same network as the charging stations.

How often do you send a getconfig? Wouldn't sending a "none" command work?

What i don't understand is that if the websocket is closed, why do i still get meter values from the charging stations but commands drop with errors? Shouldn't it be both?

**Comment by yonas124** [comment]
@gvregulvar yes, my thought as well, but the error is only from CP to CS (commands). I send it every hour to check if the server receive any reply or not.
My setup is a bit different, it's in a cloud VPS with 3 chargers connecting over 3G/4G sim.

**Comment by gvregulvar** [comment]
Strangely enough, i didn't have any charging stations disconnect from my server this morning...

**Comment by gvregulvar** [comment]
@yonas124 Im curious, how much data are you using with the charging stations sending data (on 4g) every x amount of time?

**Comment by gvregulvar** [comment]
Im getting closed websockets even while sending queries now. Have you tried the solution @mingyi621 talked before @yonas124?

**Comment by yonas124** [comment]
@gvregulvar I have and as I mentioned before, no error but after a while charger doesn't respond to query from server. This is why I setup periodic query sending to check if there's any reply or not.

**Comment by gvregulvar** [comment]
Oh i didn't catch that. Thanks for replying. Sorry for tagging you twice in a row, wasn't intended.

Have a good one!

**Comment by gvregulvar** [comment]
I just wanted to update the thread in case someone land here from google :

The workaround proposed by yonas along with the first solution by ming works 100%. I had the server open for 3 days without a reset and the websockets are still going strong.

**Comment by yonas124** [comment]
@gvregulvar how is it going so far?
I still have some issue with charger doesn't respond to query from server after several hours after restarting flow, and it requires restart again.

I also notice that node-red is actually listening on tcp6 instead of tcp

**Comment by JasonStonier** [comment]
I have a very similar problem which I can make repeatable for testing: if the CS is running and and communicating, but then I power cycle the charge point, the CP send a boot notification up to the CS which is received, but the CS cannot send commands back down to the CP because it is communicating (I believe) on the old Web Socket. 

The way to fix this is to restart the flow, which re-establishes all the Web Sockets - which is ok if you have 1 CP, but if you have 2 or more it's not a great way of doing things because you could kill a session on one that's working perfectly. 

What I would love is a way to restart individual web sockets on a CP basis - is that possible?

**Comment by JasonStonier** [comment]
By the way, we did the trick of uncommenting lines 351 and 352 which allows (as far as I can see) the listener service to close a web socket, and it appears to have solved my problem - at least in the short tests we've done today.

**Comment by owen95t** [comment]
Unfortunately, this still happens with lines 351 and 352 commented out. This is on the latest version too (1.2.0) which comes with those lines commented. 

Any idea still? It usually happens when the charger disconnects and reconnects.

**Comment by bnystrom** [comment]
Sorry this sat for so long. Merged in the uncommenting of the two referenced lines in the server code.
Fixed in v1.3.2
#34 #35
