### ISSUE TITLE
No connection to CentralSystem@8834

### ISSUE THREAD

**Issue by thomas345** [Argonne-National-Laboratory/node-red-contrib-ocpp#44]
Trying to install node red ocpp on the latest Raspbian and Node-red. I cannot get the CentralSystem@8834 node to show anything else than "Waiting..." despite using the example in the import menu.

Node-RED version: v3.0.2
Node.js  version: v18.13.0 (also tried other versions without success)
Linux 6.2.0-1004-raspi arm LE
node-red-contrib-ocpp 1.3.4

I have an older node-red-contrib-ocpp 1.0.11 on an Ubuntu install with node js 19.3.0 that works fine, so I am a bit confused to what is wrong.

The listener is running according to ss -tulpn | grep LISTEN:

tcp   LISTEN 0      511                             0.0.0.0:1880       0.0.0.0:*    users:(("node-red",pid=737,fd=21))                   
tcp   LISTEN 0      4096                      127.0.0.53%lo:53         0.0.0.0:*    users:(("systemd-resolve",pid=503,fd=14))            
tcp   LISTEN 0      4096                         127.0.0.54:53         0.0.0.0:*    users:(("systemd-resolve",pid=503,fd=16))            
tcp   LISTEN 0      4096                                  *:22               *:*    users:(("sshd",pid=631,fd=3),("systemd",pid=1,fd=68))
tcp   LISTEN 0      511                                   *:8834             *:*    users:(("node-red",pid=737,fd=20))  

Update:
The log shows:
node: CentralSystem@8834 	 type: info 	 data: Ready to recieve websocket requests on /ocpp/:cbid

**Comment by bnystrom** [comment]
Check the setup of you EVSE node. It has a setting (checkbox) which enables
the EVSE node to not attempt to auto connect. If that is checked, you would
need to send a msgType: 99 with a command: 'connect' in order for the EVSE
to start a websocket connection to the CS/CSMS node. Older releases of the
nodes always attempted to make a websocket connection as soon as node-red
started/restarted.

Best Regards
Bryan Nystrom

**Comment by bnystrom** [comment]
closing issue
