### ISSUE TITLE
Unable to update/install 

### ISSUE THREAD

**Issue by KBisht31** [Argonne-National-Laboratory/node-red-contrib-ocpp#46]
I am unable to update the node from 1.2.1000 to 1.3.4 and cant even install the fresh palette.
running v3.0.2

**Comment by bnystrom** [comment]
Sorry to hear you are having troubles installing/upgrading. Where did you get a v 1.2.1000 ? 
Our release history goes from 1.2.0 to 1.2.2. There wasn't a 1.2.1 release (or a 1.2.1000)

You may just want to uninstall what you have and reinstall the latest.

**Comment by bnystrom** [comment]
Closing issue
