### ISSUE TITLE
Force "CS request JSON" to reconnect after charger power cycle?

### ISSUE THREAD

**Issue by john0shaw** [Argonne-National-Laboratory/node-red-contrib-ocpp#47]
Hello!

I'm having an issue where the "CS request JSON" nodes seem to lose their connection to an EV charger if the charger is power cycled / taken offline by a power interruption.  The nodes get a status of "Not connected to <chargerID>" and are no longer able to send messages.  I still receive messages via the "CS server" node.  Redeploying the flow re-establishes the connection, so I was wondering if there was a way to force these nodes to re-establish a connection without a redeploy.

**Comment by bnystrom** [comment]
Please try v1.3.5
