### ISSUE TITLE
Not Connected to CP after ~24 hours

### ISSUE THREAD

**Issue by art103** [Argonne-National-Laboratory/node-red-contrib-ocpp#48]
Running latest master (7c60fac05c9688818375056a3a7a5f473a1cefb9) on Node Red v3.0.2, although this has been going on for at least a year with previous versions of both.
I was following [issue 4](https://github.com/Argonne-National-Laboratory/node-red-contrib-ocpp/issues/4) and commenting out the removeListeners() code, but this did not fix the issue for me, nor does the latest commit (1.3.4 or tip of master).

Incoming messages from the CP are received fine, but when it comes time to start / stop a charge or change the charge current, I find that the command is ignored.

Looking at the flow graph, it says "Not Connected to XXXXX" in grey under the CP node.
There is not output at all in the console log to suggest what has gone wrong. 
Restarting the flows is the only way I can recover from this state.

What information can I gather, or what debug logging can I add to help resolve this issue?

Many thanks :-)

**Comment by bnystrom** [comment]
Please try v1.3.5
