### ISSUE TITLE
cbId field in msg.payload

### ISSUE THREAD

**Issue by mastin-zgz** [Argonne-National-Laboratory/node-red-contrib-ocpp#6]
Good morning,

Is there a way to define the "cbId" field in the "CP Client JSON" by means of a payload? It would be useful to not have too many nodes for each loader.

Thank you!

**Comment by chrisn-au** [comment]
@mastin-zgz I am pretty sure there is no way to do what you are after out of the box, it wold require  code changes to ocpp-cp-json-js to maintain state. while technically possible (seems like a bit of work to get right)  seems to go against the node-red philosophy of a  node doing one job. Have you looked at creating sub flows in node red. This will allow you to group capability and reduce duplication. In my use case the charger management side ( the charger sending/responding to non user interacting messages, heartbeat, statusConfiguration, bootNotiifcation remote start/end etc) are all common and in a subflow but only expose the user facing node like start/stop charge which will be interfaced via the dashboard.  I am sure you will have different requirements but that is how I have done it

**Comment by mastin-zgz** [comment]
@chrisn-au 
Thank you very much for the reply.

What I wanted was an easy way to configure it without having to enter node network, just the UI.

I have solved this by adding a .json in the node folder, with the parameters I want it to use when deploying.

In the ocpp-cp-json code I have added this
`var obj = require('./parametros.json'); `
and modified the variables to use those of the json.
  ` this.url = obj.wsURL;
    this.cbId = obj.cbId;` 
I do not know if it is the most optimal or elegant solution, but it has helped me to get out of trouble.

Thank you!

**Comment by chrisn-au** [comment]
If it works then that is all that really matters. The issue that you will have is when this module is updated you will loose the configuration however just something to be aware of. 

BTW why would you want many of these nodes for the same charger, I would have thought one node corresponds to one charger and having more than one per charger is likely to cause ws challenges . perhaps I am not understanding ?

**Comment by chrisn-au** [comment]
hi,

If it works great. Just be aware of potential issues with multiple instances, i would be concerned about messages getting lost

i am not sure what errors you are looking to catch , sorry not sure i can help
