### ISSUE TITLE
`pong` is send as data frame instead as control frame.

### ISSUE THREAD

**Issue by OrangeTux** [Argonne-National-Laboratory/node-red-contrib-ocpp#8]
@Ataraxiall [reported an intergration problem](https://github.com/mobilityhouse/ocpp/issues/99) between this repo and [a Python implementation of OCPP](https://github.com/mobilityhouse/ocpp).

It turned out that this project responds to `ping` messages by sending a `pong`  messages as a data frame instead as a control frame:

https://github.com/Argonne-National-Laboratory/node-red-contrib-ocpp/blob/f85c90a26d3ad228031c86e4733620f81b0bb795/ocpp/ocpp-cp-json.js#L149-L152

I think the code should be changed to use [`ws.pong`](https://github.com/websockets/ws/blob/HEAD/doc/ws.md#websocketpongdata-mask-callback) instead of `ws.send('pong')`.

**Comment by jayharper** [comment]
This issue has been fixed: d6fc834dcb421fcdf82d0743f100effb04d865c9
Closing.
